apiVersion: v1
data:
  gencsv.sh: "#!/bin/bash\n\nrm inputFile\n\nif [[ \"${1}\" -eq 0 ]]\nthen\n\tfor
    INDEX in {0..9}\n\tdo\n\t\tVALUE=$(echo ${RANDOM}|head -c2)\n\t\techo \"${INDEX},
    ${VALUE}\" >> inputFile\n\tdone\n\texit 1\nfi\n\nif [[ \"${1}\" -gt 0 ]]\nthen\n\tfor
    INDEX in $(seq 0 ${1})\n\tdo\n\t\tVALUE=$(echo ${RANDOM}|head -c2)\n                echo
    \"${INDEX}, ${VALUE}\" >> inputFile\n        done\n        exit 1\nfi\n\n"
  inputFile: |
    0, 12
    1, 10
    2, 72
    3, 25
    4, 31
    5, 22
    6, 13
    7, 23
    8, 39
    9, 66
  prometheus.yml: |
    global:
      scrape_interval:     15s
      evaluation_interval: 15s

    scrape_configs:
      - job_name: 'csvserver'
        scrape_interval: 5s
        metrics_path: /metrics
        static_configs:
          - targets: ['csvserver:9300']
kind: ConfigMap
metadata:
  name: csv-prom
