apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: csvserver
  name: csvserver
spec:
  replicas: 1
  selector:
    matchLabels:
      app: csvserver
  strategy: {}
  template:
    metadata:
      labels:
        app: csvserver
    spec:
      containers:
      - image: infracloudio/csvserver:latest
        name: csvserver
        volumeMounts:
          - mountPath: /csvserver/inputdata
            name: config
            readOnly: true
            subPath: inputFile
      volumes:
        - name: config
          configMap:
            name: csv-prom

---
apiVersion: v1
kind: Service
metadata:
  name: csvserver
spec:
  selector:
    app: csvserver
  ports:
  - name: csvserver
    port: 9300
    targetPort: 9300