apiVersion: v1
data:
  gencsv.sh: |
    #!/bin/bash
    ARG=${1}
    if [[ "${ARG}" -eq 0 ]]
    then
      ARG=9
    fi
    for INDEX in $(seq 0 ${ARG})
      do
        VALUE=$(echo ${RANDOM}|head -c2)
        echo "${INDEX}, ${VALUE}" >> /csvserver/inputdata
      done
  inputFile: |
    0, 12
    1, 10
    2, 72
    3, 25
    4, 31
    5, 22
    6, 13
    7, 23
    8, 39
    9, 66
  prometheus.yml: |
    global:
      scrape_interval:     15s
      evaluation_interval: 15s

    scrape_configs:
      - job_name: 'csvserver'
        scrape_interval: 5s
        metrics_path: /metrics
        static_configs:
          - targets: ['csvserver:9300']
kind: ConfigMap
metadata:
  name: csv-prom
